CLASS zbp_r_mjl_employee DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zr_mjl_employee.
    PROTECTED SECTION.

    PRIVATE SECTION.


ENDCLASS.

CLASS zbp_r_mjl_employee IMPLEMENTATION.
ENDCLASS.
